# Site settings
title: darius s. Freelance Web Developer. London
title_header: darius s.
full_name: Darius Scerbavicius
email: darius.scerb@gmail.com
description: "Software Engineer / Freelance Developer / London"
baseurl: ""
url: "http://dariuss.net"
github_username: darka
twitter_username: scdarius

# Build settings
markdown: kramdown
permalink: pretty
