# Site settings
title: darius s.
full_name: Darius Scerbavicius
email: darius.scerb@gmail.com
description: "Software Engineer / Entrepreneur / Edinburgh"
baseurl: ""
url: "http://dariuss.net"
github_username: darka
twitter_username: scdarius

# Build settings
markdown: kramdown
permalink: pretty
