# Site settings
title: "Darius Scerbavicius | blog"
title_header: "dariuss.net"
full_name: Darius Scerbavicius
email: darius.scerb@gmail.com
description: "Software Engineer / Freelance Developer / London"
baseurl: ""
url: "http://dariuss.net"
github_username: darka
twitter_username: scdarius

# Build settings
markdown: kramdown
permalink: pretty
